server:
  port: 8081

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.40.230.136:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: MISAKIRINNE
    password: misaki123


eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为:true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为:true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka #,http://eureka7002.com:7002/eureka
  instance:
    # hostname:
    instance-id: payment8081
    prefer-ip-address: true