server:
  port: 8082

eureka:
  client:
    # 表示是否将自己注册进EurekaServer 默认为:true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为:true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    # hostname:
    instance-id: order8082
    prefer-ip-address: true